import Hero from '@/components/Frontpage/Hero/Hero';
import Head from 'next/head';
import React from 'react'
import About from '@/components/About/about';
const AboutUs = ({Data})=>{
    return(
        <>
            <Head>
                <title>Pro Football::About us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
            <About />
            
        </>
    )
}

export default AboutUs;

