import Hero from '@/components/Frontpage/Hero/Hero';
import Head from 'next/head';
import React from 'react'
import Contact from '@/components/Contact/contact';
const ContactUs = ({Data})=>{
    return(
        <>
            <Head>
                <title>Pro Football::Contact us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
            <Contact />
            
        </>
    )
}

export default ContactUs;

